name: Simple Warp
author: happyzombie707
description: This is a plugin that allows you to manage warp points!
main: org.happyzombie.WarpMain
version: 1.0
commands:
   warp:
      description: The base for Simple warps
      usage: /<command>
   warp help:
      description: Help with the SimpleWarp plugin.
      usage: /warp <command>
   warp set:
      description: This sets a warp.
      usage: /warp <command> [name]
   warp delete:
      description: This deletes a warp.
      usage: /warp <command> [name]
   warp to:
      description: This warps someone to a warp. Don't inclde a player to warp yourself.
      usage: /warp <command> [name] [player]
   warp list:
      description: Lists all the warps in the current world.
      usage: /warp <command>
   warp compass:
      description: Sets your compass to point to a warp.
      usage: /warp <command>
   warp save:
      description: Saves warps
      usage: /warp <command>
   warp beacon:
      description: Strike a warp with lightning.
      usage: /warp <command>
   warp info:
      description: Show details about a warp.
      usage: /warp info [name]